/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bottom: (typeof import('./src/components/bottom/index.vue'))['default']
    Components: (typeof import('./src/components/index.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRaw: (typeof import('element-plus/es'))['ElRaw']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Top: typeof import('./src/components/top/index.vue')['default']
  }
}
